window.LOGO_SRC = "/media/logo.webp";
window.PRODUCT_IMAGES = {
  img1: "/media/bangle-1.webp",
  img2: "/media/bangle-2.webp",
  img3: "/media/bangle-3.webp",
  img4: "/media/bangle-4.webp",
  img5: "/media/bangle-5.webp",
  img6: "/media/bangle-6.webp",
  img7: "/media/bangle-7.webp",
  img8: "/media/bangle-8.webp",
  img9: "/media/bangle-9.webp",
  img10: "/media/bangle-10.webp",
  img11: "/media/bangle-11.webp",
  img12: "/media/bangle-12.webp",
  img13: "/media/bangle-13.webp",
  img14: "/media/bangle-14.webp",
  img15: "/media/bangle-15.webp",
  img16: "/media/bangle-16.webp",
  img17: "/media/bangle-17.webp",
  img18: "/media/bangle-18.webp",
  img19: "/media/bangle-19.webp",
  img20: "/media/bangle-20.webp",
  img21: "/media/bangle-21.webp",
  img22: "/media/bangle-22.webp",
  img23: "/media/bangle-23.webp",
  img24: "/media/bangle-24.webp",
  img25: "/media/bangle-25.webp",
  img26: "/media/bangle-26.webp",
  img27: "/media/bangle-27.webp",
  img28: "/media/bangle-28.webp",
  img29: "/media/bangle-29.webp",
  img30: "/media/bangle-30.webp",
  img31: "/media/bangle-31.webp",
  img32: "/media/bangle-32.webp",
  img33: "/media/bangle-33.webp",
};;
